"""initial commit

Revision ID: 51a805dfe28d
Revises: 
Create Date: 2026-04-27 19:00:05.794173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from core.config import settings

# revision identifiers, used by Alembic.
revision: str = '51a805dfe28d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='fastapi_app'
    )
    op.create_table('blog_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_app'
    )
    op.create_index(op.f('ix_application_blog_category_slug'), 'blog_category', ['slug'], unique=True, schema='fastapi_app')
    op.create_table('blog_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_app'
    )
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('category_slug', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['fastapi_app.auth_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_slug'], ['fastapi_app.blog_category.slug'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['fastapi_app.blog_location.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_app'
    )
    op.create_table('blog_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['fastapi_app.auth_user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['fastapi_app.blog_post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_comment', schema='fastapi_app')
    op.drop_table('blog_post', schema='fastapi_app')
    op.drop_table('blog_location', schema='fastapi_app')
    op.drop_index(op.f('ix_application_blog_category_slug'), table_name='blog_category', schema='fastapi_app')
    op.drop_table('blog_category', schema='fastapi_app')
    op.drop_table('auth_user', schema='fastapi_app')
    # ### end Alembic commands ###